// import { generateText } from '../../utils/loremIpsumGenerator';

export const stubState = {
  channels: [
    {
      url: 'sendbird_group_channel_82871107_a',
      members: [
        {
          connectionStatus: 'online',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          isBlockedByMe: false,
          isBlockingMe: false,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'Melvyn',
          profileUrl: '',
          state: 'joined',
          userId: 'sngguojie@gmail.com',
        },
        {
          connectionStatus: 'offline',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          isBlockedByMe: false,
          isBlockingMe: false,
          lastSeenAt: 1541510398187,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          state: 'joined',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      ],
    },
    {
      url: 'sendbird_group_channel_82871107_b',
      members: [
        {
          connectionStatus: 'online',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          isBlockedByMe: false,
          isBlockingMe: false,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'Melvyn',
          profileUrl: '',
          state: 'joined',
          userId: 'sngguojie@gmail.com',
        },
        {
          connectionStatus: 'online',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          isBlockedByMe: false,
          isBlockingMe: false,
          lastSeenAt: 1541510398187,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin2',
          profileUrl: '',
          state: 'joined',
          userId: 'sghomeneeds.dev2@gmail.com',
        },
      ],
    },
  ],
  messages: {
    sendbird_group_channel_82871107_a: [
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_a',
        createdAt: 1541493575425,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message: 'd',
        messageId: 1933673031,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'Melvyn',
          profileUrl: '',
          userId: 'sngguojie@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_a',
        createdAt: 1541608548104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message: 'Test',
        messageId: 1934161902,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
    ],
    sendbird_group_channel_82871107_b: [
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541493575425,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message: 'd',
        messageId: 1933673031,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'Melvyn',
          profileUrl: '',
          userId: 'sngguojie@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message:
          'Test this is a really long last msg test test\nMultiline and long also like really really really really long messsage that needs to be wrapped or else its really ugly.\n\nMore multiline stuff!',
        messageId: 1934161901,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message:
          'Test this is a really long last msg test test\nMultiline and long also like really really really really long messsage that needs to be wrapped or else its really ugly.\n\nMore multiline stuff!',
        messageId: 1934161903,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message:
          'Test this is a really long last msg test test\nMultiline and long also like really really really really long messsage that needs to be wrapped or else its really ugly.\n\nMore multiline stuff!',
        messageId: 1934161904,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message:
          'Test this is a really long last msg test test\nMultiline and long also like really really really really long messsage that needs to be wrapped or else its really ugly.\n\nMore multiline stuff!',
        messageId: 1934161905,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message:
          'Test this is a really long last msg test test\nMultiline and long also like really really really really long messsage that needs to be wrapped or else its really ugly.\n\nMore multiline stuff!',
        messageId: 1934161906,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message:
          'Just to confirm, your address is:\nAddress Line 1\nAddress Line2\n#unit-number\n\nCorrect?',
        messageId: 1934161907,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'SGHomeNeedsAdmin',
          profileUrl: '',
          userId: 'sghomeneeds.dev@gmail.com',
        },
      },
      {
        channelType: 'group',
        channelUrl: 'sendbird_group_channel_82871107_b',
        createdAt: 1541509598104,
        customType: '',
        data: '',
        mentionType: 'users',
        mentionedUsers: [],
        message: 'Yes thanks',
        messageId: 1934161908,
        messageType: 'user',
        metaArray: {},
        reqId: '',
        translations: {},
        updatedAt: 0,
        _sender: {
          connectionStatus: 'nonavailable',
          friendDiscoveryKey: null,
          friendName: null,
          isActive: true,
          lastSeenAt: 0,
          metaData: {},
          nickname: 'Melvyn',
          profileUrl: '',
          userId: 'sngguojie@gmail.com',
        },
      },
    ],
  },
  selectedChannel: { url: null },
  connected: false,
  channelHandler: null,
};
