export function generateText(numChar) {
  const text =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Montes nascetur ridiculus mus mauris vitae ultricies. Integer eget aliquet nibh praesent tristique. Non tellus orci ac auctor augue mauris augue. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Id consectetur purus ut faucibus. Vel eros donec ac odio. In pellentesque massa placerat duis ultricies. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Turpis egestas pretium aenean pharetra magna. Id neque aliquam vestibulum morbi blandit cursus risus.\n' +
    '\n' +
    'Orci porta non pulvinar neque laoreet suspendisse interdum. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Ac auctor augue mauris augue neque gravida in fermentum et. Ut diam quam nulla porttitor massa id. Aliquet nibh praesent tristique magna sit. Accumsan lacus vel facilisis volutpat. Quis varius quam quisque id diam vel quam. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Enim diam vulputate ut pharetra sit. Nec nam aliquam sem et tortor consequat id porta. Eget nunc lobortis mattis aliquam faucibus purus in massa. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Sed arcu non odio euismod lacinia at. Lectus nulla at volutpat diam ut venenatis tellus in metus. Proin sed libero enim sed faucibus. Non blandit massa enim nec. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Velit dignissim sodales ut eu sem integer.\n' +
    '\n' +
    'Pellentesque dignissim enim sit amet venenatis urna cursus eget. Augue mauris augue neque gravida in. Consequat nisl vel pretium lectus quam id. Tincidunt tortor aliquam nulla facilisi. Diam ut venenatis tellus in. Et tortor consequat id porta. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. At lectus urna duis convallis convallis tellus id interdum. Ut consequat semper viverra nam libero justo laoreet sit. Enim neque volutpat ac tincidunt vitae semper.\n' +
    '\n' +
    'Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Condimentum vitae sapien pellentesque habitant morbi tristique. Mi bibendum neque egestas congue quisque egestas. Proin fermentum leo vel orci porta non pulvinar. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Placerat vestibulum lectus mauris ultrices. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Odio ut sem nulla pharetra diam sit amet nisl. Nunc sed augue lacus viverra vitae congue. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Risus sed vulputate odio ut enim blandit. Odio euismod lacinia at quis risus. Et sollicitudin ac orci phasellus.\n' +
    '\n' +
    'Elit eget gravida cum sociis natoque penatibus et magnis. Velit ut tortor pretium viverra. Nibh tellus molestie nunc non blandit massa enim. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Interdum velit euismod in pellentesque massa placerat duis ultricies. Rutrum quisque non tellus orci. Nunc pulvinar sapien et ligula. Purus viverra accumsan in nisl nisi. Euismod in pellentesque massa placerat. Semper auctor neque vitae tempus quam pellentesque. Turpis egestas maecenas pharetra convallis posuere.';
  return text.slice(0, numChar);
}
