export const categories = [
  { name: 'Interior Designers', parent: 'Home Remodeling' },
  { name: 'Defect Checking', parent: 'Home Remodeling' },
  { name: 'Fengshui Masters', parent: 'Home Remodeling' },
  { name: 'Lighting Plan', parent: 'Home Remodeling' },
  { name: 'Renovation', parent: 'Home Remodeling' },
  { name: 'Architects & Building Designers', parent: 'Home Remodeling' },
  { name: 'Air-conditioner', parent: 'Air-conditioning & Cooling' },
  { name: 'Fans', parent: 'Air-conditioning & Cooling' },
  {
    name: 'Outdoor Mist Cooling System',
    parent: 'Air-conditioning & Cooling',
  },
  { name: 'Refrigeration', parent: 'Air-conditioning & Cooling' },
  { name: 'Cabinets', parent: 'Built-In Furniture' },
  { name: 'Countertops', parent: 'Built-In Furniture' },
  { name: 'Carpenters', parent: 'Carpentry & Woodworking' },
  { name: 'Cabinets & Countertops', parent: 'Carpentry & Woodworking' },
  { name: 'Decks, Fences & Ramps', parent: 'Carpentry & Woodworking' },
  { name: 'Doors', parent: 'Carpentry & Woodworking' },
  { name: 'Framing', parent: 'Carpentry & Woodworking' },
  { name: 'Blinds', parent: 'Curtains, Blinds & Shades' },
  { name: 'Curtains', parent: 'Curtains, Blinds & Shades' },
  {
    name: 'Electronic Drape, Shade or Blind Opener',
    parent: 'Curtains, Blinds & Shades',
  },
  { name: 'Roller Blinds', parent: 'Curtains, Blinds & Shades' },
  { name: 'Shades', parent: 'Curtains, Blinds & Shades' },
  { name: 'Carpet Cleaning', parent: 'Cleaning Services' },
  { name: 'Draperies & Blinds', parent: 'Cleaning Services' },
  { name: 'Furniture Cleaning', parent: 'Cleaning Services' },
  { name: 'Home Dry Cleaning & Laundry', parent: 'Cleaning Services' },
  { name: 'Mattress Cleaning', parent: 'Cleaning Services' },
  { name: 'Part Time Cleaners', parent: 'Cleaning Services' },
  { name: 'Post Construction Clean Up', parent: 'Cleaning Services' },
  { name: 'Waste Material & Junk Removal', parent: 'Cleaning Services' },
  { name: 'Window Cleaning', parent: 'Cleaning Services' },
  { name: 'Wall & Ceiling Cleaning', parent: 'Cleaning Services' },
  { name: 'Electricians', parent: 'Electrical' },
  { name: 'Appliances', parent: 'Electrical' },
  { name: 'Cables, Networks & Telephones', parent: 'Electrical' },
  { name: 'Light Wiring', parent: 'Electrical' },
  { name: 'Outlets, Panels, Switches & Wiring', parent: 'Electrical' },
  { name: 'Water Filtration', parent: 'Electrical' },
  { name: 'Water Heaters', parent: 'Electrical' },
  {
    name: 'Energy Efficient Windows and Doors',
    parent: 'Energy Efficient Home',
  },
  { name: 'Home Solar Energy', parent: 'Energy Efficient Home' },
  { name: 'Brick & Stone', parent: 'Flooring' },
  { name: 'Carpeted Flooring ', parent: 'Flooring' },
  { name: 'Concrete', parent: 'Flooring' },
  { name: 'Hardwood', parent: 'Flooring' },
  { name: 'Laminate & Vinyl', parent: 'Flooring' },
  { name: 'Sports Surfaces', parent: 'Flooring' },
  { name: 'Synthetic Grass', parent: 'Flooring' },
  { name: 'Floor Tiles', parent: 'Flooring' },
  { name: 'Electricians', parent: 'Handyman Services' },
  { name: 'Handyman', parent: 'Handyman Services' },
  { name: 'Plumbers', parent: 'Handyman Services' },
  { name: 'Waterproofing', parent: 'Handyman Services' },
  { name: 'Elevator', parent: 'Home Automation' },
  { name: 'Smart Home', parent: 'Home Automation' },
  { name: 'Furniture Collection & Disposal', parent: 'Home Movers' },
  { name: 'International Movers & Transport', parent: 'Home Movers' },
  { name: 'Local Movers & Transport', parent: 'Home Movers' },
  { name: 'Storage', parent: 'Home Movers' },
  { name: 'Waste Material & Junk Removal', parent: 'Home Movers' },
  { name: 'Biometrics Locks', parent: 'Home Security' },
  { name: 'CCTV & Cameras', parent: 'Home Security' },
  { name: 'Home Alarms & Security', parent: 'Home Security' },
  { name: 'Locksmiths', parent: 'Home Security' },
  { name: 'Home Theatre Surround Sound System', parent: 'Home Theater' },
  { name: 'Home Theatre System or Media Center ', parent: 'Home Theater' },
  { name: 'Full Time Maid', parent: 'Maid Service' },
  { name: 'Part Time Maid', parent: 'Maid Service' },
  { name: 'Maids For The Young', parent: 'Maid Service' },
  { name: 'Maids For Seniors', parent: 'Maid Service' },
  { name: 'Awnings & Patio Covers', parent: 'Outdoor Home' },
  { name: 'Decks, Porches & Patios', parent: 'Outdoor Home' },
  { name: 'Fences', parent: 'Outdoor Home' },
  { name: 'Foundations', parent: 'Outdoor Home' },
  { name: 'Landscape, Yard & Garden', parent: 'Outdoor Home' },
  { name: 'Exterior Painting or Staining', parent: 'Painting & Staining' },
  { name: 'Interior Painting or Staining', parent: 'Painting & Staining' },
  { name: 'Paint Removal and Cleaning', parent: 'Painting & Staining' },
  { name: 'Special Finishes', parent: 'Painting & Staining' },
  { name: 'Wallpapering', parent: 'Painting & Staining' },
  { name: 'Mould Cleaning', parent: 'Pest Control' },
  { name: 'Pest Control Services', parent: 'Pest Control' },
  { name: 'Roofings & Gutters', parent: 'Roofing & Gutters' },
  { name: 'Roofing and Gutters Cleaning', parent: 'Roofing & Gutters' },
  { name: 'Maids For Seniors', parent: 'Senior Caretaker' },
  { name: 'Senior Housing Material & Design', parent: 'Senior Caretaker' },
  { name: 'Senior In-House Care', parent: 'Senior Caretaker' },
  {
    name: 'Hot Tubs & Spa',
    parent: 'Swimming Pools, Spas, Hot Tubs & Saunas',
  },
  { name: 'Saunas', parent: 'Swimming Pools, Spas, Hot Tubs & Saunas' },
  {
    name: 'Swimming Pool',
    parent: 'Swimming Pools, Spas, Hot Tubs & Saunas',
  },
  {
    name: 'Swimming Pool Decks & Patios',
    parent: 'Swimming Pools, Spas, Hot Tubs & Saunas',
  },
  { name: 'Ceiling', parent: 'Walls & Ceiling' },
  { name: 'Soundproofing', parent: 'Walls & Ceiling' },
  { name: 'Tile', parent: 'Walls & Ceiling' },
  { name: 'Wallcoverings', parent: 'Walls & Ceiling' },
  { name: 'Wall & Ceiling Cleaning', parent: 'Walls & Ceiling' },
  { name: 'Doors', parent: 'Windows and Doors' },
  { name: 'Glass & Mirrors', parent: 'Windows and Doors' },
  { name: 'Locksmiths', parent: 'Windows and Doors' },
  { name: 'Screens, Films & Tints', parent: 'Windows and Doors' },
  { name: 'Windows', parent: 'Windows and Doors' },
  { name: 'Window Cleaning', parent: 'Windows and Doors' },
  { name: 'Babysitter', parent: 'Young Caretaker' },
  { name: 'Nanny', parent: 'Young Caretaker' },
  { name: 'Maids For The Young', parent: 'Young Caretaker' },
];
